spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initialSize: 10
      minIdle: 10
      maxActive: 100
      maxWait: 1000
  jackson:
    time-zone: GMT+8


mybatis:
    #mapper.xml文件所在的路径
    mapperLocations: classpath:mappers/*.xml
    typeAliasesPackage: tk.mapper.model

logging:
  level:
    #mapper.class文件所在的路径
    com.zzh.mappers: debug
    com.ibatis.sqlmaps: debug

server:
  port: 18080
  context-path: /zzh

