spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initialSize: 10
      minIdle: 10
      maxActive: 100
      maxWait: 1000
  jackson:
    time-zone: GMT+8
  redis:
    cluster:
      max-redirects:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0


mybatis:
    #mapper.xml文件所在的路径
    mapperLocations: classpath:mappers/*.xml
    typeAliasesPackage: tk.mapper.model

logging:
  level:
    #mapper.class文件所在的路径
    com.zzh.mappers: debug
    com.ibatis.sqlmaps: debug

#server
server:
  port: 18080
  context-path: /zzh

#AES key
com:
  zzh:
    key: 52125ad5baf8b04567702ac9842479fa

#zabbix
zabbix:
  server:
    url: http://192.168.42.144
    user: Admin
    passwd: zabbix

# security
security:
  user:
    name: admin
    password: admin